### ISSUE TITLE
Sometimes, not all streams appear on the home page

### ISSUE THREAD

**Issue by supriyaamisshra** [moonshotcollective/tokenstream.party#44]
Sometimes, not all streams show up on the home page

Due to async loading of the stream data, the order of arrival of responses is not guaranteed so there can be cases where a smaller list of streams replace a larger list of streams on the home page component.

**Comment by supriyaamisshra** [comment]
I have thought of a solution for this.

**Comment by codenamejason** [comment]
I patched it but more of a bandaid for now
